openapi: 3.0.3
info:
  title: Product Management API
  version: 1.0.0
  description: API for product management

paths:
  /products:
    get:
      summary: Get all products
      tags:
        - ProductQueries
      operationId: getAllProducts
      description: Retrieves a list of all products.
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductView'

components:
  schemas:
    ProductView:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the product
          example: 1
        name:
          type: string
          description: The name of the product
          example: "Product 1"
        description:
          type: string
          description: The description of the product
          example: "This is product 1"
        coverageDescription:
          type: string
          description: The coverage of the product
          example: "this is a coverage description"
        category:
          type: string
          description: The category of the product
          example: "CAR"
        coverageCategory:
          type: string
          description: The coverage category of the product
          example: "BASIC"
        price:
          type: array
          items:
            $ref: '#/components/schemas/PriceView'

    PriceView:
      type: object
      properties:
        amount:
          type: number
          format: double
          description: The amount of the price
          example: 100.00
        paymentCycle:
          type: string
          description: The payment cycle of the price
          example: "MONTHLY"
