openapi: 3.0.3
info:
  title: User Management API
  version: 1.0.0
  description: API for user management and chat service

paths:
  /users/sign-up:
    post:
      summary: Sign up a new user
      tags:
        - UserCommands
      operationId: signUpUser
      description: Creates a new user with the provided details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserSignUpPayload'
      responses:
        "201":
          description: User successfully created
        "400":
          description: Bad request
        "409":
          description: Conflict

  /users/{id}:
    get:
      summary: Get a user by ID
      tags:
        - UserQueries
      operationId: getUserById
      description: Retrieves a user by their unique ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserView'
        '404':
          description: User not found

  /users:
    get:
      summary: Get all users
      tags:
        - UserQueries
      operationId: getAllUsers
      description: Retrieves a list of all users.
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserView'

components:
  schemas:
    UserSignUpPayload:
      type: object
      properties:
        username:
          type: string
          format: email
          description: The email address of the user
          example: "user@example.com"
        firstName:
          type: string
          description: The user's first name
          example: "John"
        lastName:
          type: string
          description: The user's last name
          example: "Doe"

    UserView:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the user
          example: 1
        username:
          type: string
          format: email
          description: The email address of the user
          example: "user@example.com"
        firstName:
          type: string
          description: The user's first name
          example: "John"
        lastName:
          type: string
          description: The user's last name
          example: "Doe"
