/* tslint:disable */
/* eslint-disable */
/**
 * User Management API
 * API for user management and chat service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PriceView
 */
export interface PriceView {
    /**
     * The amount of the price
     * @type {number}
     * @memberof PriceView
     */
    amount?: number;
    /**
     * The payment cycle of the price
     * @type {string}
     * @memberof PriceView
     */
    paymentCyle?: string;
}

/**
 * Check if a given object implements the PriceView interface.
 */
export function instanceOfPriceView(value: object): value is PriceView {
    return true;
}

export function PriceViewFromJSON(json: any): PriceView {
    return PriceViewFromJSONTyped(json, false);
}

export function PriceViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceView {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'paymentCyle': json['paymentCyle'] == null ? undefined : json['paymentCyle'],
    };
}

export function PriceViewToJSON(value?: PriceView | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
        'paymentCyle': value['paymentCyle'],
    };
}

