/* tslint:disable */
/* eslint-disable */
/**
 * User Management API
 * API for user management and chat service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProductView,
} from '../models/index';
import {
    ProductViewFromJSON,
    ProductViewToJSON,
} from '../models/index';

/**
 * 
 */
export class ProductQueriesApi extends runtime.BaseAPI {

    /**
     * Retrieves a list of all products.
     * Get all products
     */
    async getAllProductsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProductView>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/products`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductViewFromJSON));
    }

    /**
     * Retrieves a list of all products.
     * Get all products
     */
    async getAllProducts(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProductView>> {
        const response = await this.getAllProductsRaw(initOverrides);
        return await response.value();
    }

}
