/* tslint:disable */
/* eslint-disable */
/**
 * Product Management API
 * API for product management
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceView } from './PriceView';
import {
    PriceViewFromJSON,
    PriceViewFromJSONTyped,
    PriceViewToJSON,
} from './PriceView';

/**
 * 
 * @export
 * @interface ProductView
 */
export interface ProductView {
    /**
     * Unique identifier for the product
     * @type {string}
     * @memberof ProductView
     */
    id?: string;
    /**
     * The name of the product
     * @type {string}
     * @memberof ProductView
     */
    name?: string;
    /**
     * The description of the product
     * @type {string}
     * @memberof ProductView
     */
    description?: string;
    /**
     * The coverage of the product
     * @type {string}
     * @memberof ProductView
     */
    coverageDescription?: string;
    /**
     * The category of the product
     * @type {string}
     * @memberof ProductView
     */
    category?: string;
    /**
     * The coverage category of the product
     * @type {string}
     * @memberof ProductView
     */
    coverageCategory?: string;
    /**
     * 
     * @type {Array<PriceView>}
     * @memberof ProductView
     */
    price?: Array<PriceView>;
}

/**
 * Check if a given object implements the ProductView interface.
 */
export function instanceOfProductView(value: object): value is ProductView {
    return true;
}

export function ProductViewFromJSON(json: any): ProductView {
    return ProductViewFromJSONTyped(json, false);
}

export function ProductViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductView {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'coverageDescription': json['coverageDescription'] == null ? undefined : json['coverageDescription'],
        'category': json['category'] == null ? undefined : json['category'],
        'coverageCategory': json['coverageCategory'] == null ? undefined : json['coverageCategory'],
        'price': json['price'] == null ? undefined : ((json['price'] as Array<any>).map(PriceViewFromJSON)),
    };
}

export function ProductViewToJSON(value?: ProductView | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'coverageDescription': value['coverageDescription'],
        'category': value['category'],
        'coverageCategory': value['coverageCategory'],
        'price': value['price'] == null ? undefined : ((value['price'] as Array<any>).map(PriceViewToJSON)),
    };
}

