/* tslint:disable */
/* eslint-disable */
/**
 * User Management API
 * API for user management and chat service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSignUpPayload
 */
export interface UserSignUpPayload {
    /**
     * The email address of the user
     * @type {string}
     * @memberof UserSignUpPayload
     */
    username?: string;
    /**
     * The user's first name
     * @type {string}
     * @memberof UserSignUpPayload
     */
    firstName?: string;
    /**
     * The user's last name
     * @type {string}
     * @memberof UserSignUpPayload
     */
    lastName?: string;
}

/**
 * Check if a given object implements the UserSignUpPayload interface.
 */
export function instanceOfUserSignUpPayload(value: object): value is UserSignUpPayload {
    return true;
}

export function UserSignUpPayloadFromJSON(json: any): UserSignUpPayload {
    return UserSignUpPayloadFromJSONTyped(json, false);
}

export function UserSignUpPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSignUpPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
    };
}

export function UserSignUpPayloadToJSON(value?: UserSignUpPayload | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'username': value['username'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

