/* tslint:disable */
/* eslint-disable */
/**
 * User Management API
 * API for user management and chat service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserView
 */
export interface UserView {
    /**
     * Unique identifier for the user
     * @type {number}
     * @memberof UserView
     */
    id?: number;
    /**
     * The email address of the user
     * @type {string}
     * @memberof UserView
     */
    username?: string;
    /**
     * The user's first name
     * @type {string}
     * @memberof UserView
     */
    firstName?: string;
    /**
     * The user's last name
     * @type {string}
     * @memberof UserView
     */
    lastName?: string;
}

/**
 * Check if a given object implements the UserView interface.
 */
export function instanceOfUserView(value: object): value is UserView {
    return true;
}

export function UserViewFromJSON(json: any): UserView {
    return UserViewFromJSONTyped(json, false);
}

export function UserViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserView {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'] == null ? undefined : json['username'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
    };
}

export function UserViewToJSON(value?: UserView | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'username': value['username'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
    };
}

