-- SQL insert statements for the Product entity
INSERT INTO products (id,
                      name,
                      default_description,
                      coverage_description,
                      prices,
                      category,
                      coverage_category)
VALUES ('550e8400-e29b-41d4-a716-446655440000', 
        'Basic Health Insurance',
        'This is the default description for basic health insurance.',
        'Covers basic medical expenses and hospital stays.',
        '[{"amount": 50.0, "cycle": "MONTHLY"}, {"amount": 500.0, "cycle": "YEARLY"}]', -- JSON format for prices
        'HEALTH',
        'BASIC'),
       ('550e8400-e29b-41d4-a716-446655440001', 
        'Comprehensive Auto Insurance',
        'This is the default description for comprehensive auto insurance.',
        'Covers damages, theft, and liability for accidents.',
        '[{"amount": 70.0, "cycle": "MONTHLY"}, {"amount": 750.0, "cycle": "YEARLY"}]', -- JSON format for prices
        'AUTO',
        'PREMIUM'),
       ('550e8400-e29b-41d4-a716-446655440002', 
        'Property Insurance',
        'This is the default description for property insurance.',
        'Covers damages to property caused by fire, theft, and natural disasters.',
        '[{"amount": 100.0, "cycle": "MONTHLY"}, {"amount": 1000.0, "cycle": "YEARLY"}]', -- JSON format for prices
        'PROPERTY',
        'ADVANCED'),
       ('550e8400-e29b-41d4-a716-446655440003', 
        'Liability Insurance',
        'This is the default description for liability insurance.',
        'Covers liability for accidents causing harm to others.',
        '[{"amount": 30.0, "cycle": "MONTHLY"}, {"amount": 300.0, "cycle": "YEARLY"}]', -- JSON format for prices
        'LIABILITY',
        'INTERMEDIATE'),
       ('550e8400-e29b-41d4-a716-446655440104', 
        'Travel Insurance',
        'This is the default description for travel insurance.',
        'Covers trip cancellations, lost luggage, and medical emergencies abroad.',
        '[{"amount": 40.0, "cycle": "MONTHLY"}, {"amount": 400.0, "cycle": "YEARLY"}]', -- JSON format for prices
        'TRAVEL',
        'STANDARD'),
       ('550e8400-e29b-41d4-a716-446655441005', 
        'Pet Insurance',
        'This is the default description for pet insurance.',
        'Covers veterinary expenses for pets.',
        '[{"amount": 20.0, "cycle": "MONTHLY"}, {"amount": 200.0, "cycle": "YEARLY"}]', -- JSON format for prices
        'PET',
        'BASIC'),
       ('550e8400-e29b-41d4-a716-446655440306', 
        'Life Insurance',
        'This is the default description for life insurance.',
        'Provides financial support to beneficiaries in the event of the policyholders death.',
        '[{"amount": 60.0, "cycle": "MONTHLY"}, {"amount" : 600.0, "cycle": "YEARLY"}]', -- JSON format for prices
        'LIFE',
        'PREMIUM'),
       ('550e8400-e29b-41d4-a716-446655443007', 
        'Home Insurance',
        'This is the default description for home insurance.',
        'Covers damages to the home and personal property.',
        '[{"amount": 80.0, "cycle": "MONTHLY"}, {"amount" : 800.0, "cycle": "YEARLY"}]', -- JSON format for prices
        'HOME',
        'ADVANCED'),
       ('550e8400-e29b-41d4-a716-446655441004', 
        'Travel Insurance',
        'This is the default description for travel insurance.',
        'Covers trip cancellations, lost luggage, and medical emergencies abroad.',
        '[{"amount" : 40.0, "cycle": "MONTHLY"}, {"amount" : 400.0, "cycle": "YEARLY"}]', -- JSON format for prices
        'TRAVEL',
        'STANDARD'),
       ('550e8400-e29b-41d4-a716-446655440505', 
        'Pet Insurance',
        'This is the default description for pet insurance.',
        'Covers veterinary expenses for pets.',
        '[{"amount": 20.0, "cycle": "MONTHLY"}, {"amount" : 200.0, "cycle": "YEARLY"}]', -- JSON format for prices
        'PET',
        'BASIC'),
       ('550e8400-e29b-41d4-a716-446655440086', 
        'Life Insurance',
        'This is the default description for life insurance.',
        'Provides financial support to beneficiaries in the event of the policyholders death.',
        '[{"amount": 60.0, "cycle": "MONTHLY"}, {"amount" : 600.0, "cycle": "YEARLY"}]', -- JSON format for prices
        'LIFE',
        'PREMIUM');
;
